# Generated by Django 4.2.17 on 2024-12-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCare', '0002_useractionlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalcard',
            name='insurance_policy_number',
        ),
        migrations.RemoveField(
            model_name='medicalcard',
            name='snils_number',
        ),
        migrations.AddField(
            model_name='medicalcard',
            name='_insurance_policy_number',
            field=models.BinaryField(default=b'1234567891234567'),  # Обратите внимание на `b''`
        ),
        migrations.AddField(
            model_name='medicalcard',
            name='_snils_number',
            field=models.BinaryField(default=b'89588048586'),  # Обратите внимание на `b''`
        ),
    ]
