# Generated by Django 4.2.17 on 2024-12-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCare', '0003_remove_medicalcard_insurance_policy_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcard',
            name='_insurance_policy_number',
            field=models.BinaryField(default=b''),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='_snils_number',
            field=models.BinaryField(default=b''),
        ),
    ]
