# Generated by Django 4.2.17 on 2024-12-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedCare', '0004_alter_medicalcard__insurance_policy_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcard',
            name='_insurance_policy_number',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='_snils_number',
            field=models.CharField(default='', max_length=255),
        ),
    ]
