name: Django CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint Code with flake8
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install flake8
          pip install -r requirements.txt

      - name: Run flake8
        run: |
          source venv/bin/activate
          flake8 . --exclude=venv --max-line-length=120

  test:
    name: Run Tests

