name: Check

on:
  push:
    branches:
      - main  # или любая другая ветка, если это необходимо


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Use your desired version of Node.js

      - name: Install dependencies
        run: npm install  # Adjust to your package manager (e.g., yarn install)

      - name: Run tests
        run: npm test  # Or whatever command runs your tests
