name: Check Code Style

on:
  push:
    branches:
      - master
      - new
  pull_request:
    branches:
      - master
      - new

jobs:
  checkcode:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Check python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          pip install pycodestyle

      - name: Run Linter
        run: |
          pycodestyle